# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b17745dfa67d3946129611c8752f943ee85eba6c9f9a7c07a0e424879dcfbfa0a74b79e16aa973cd03ac57eab00e0ce6a376885b152e92db2ee25ffb94755d5

test:
  secret_key_base: 15a713001d81a76ed4f340526ca3f225751c73a438650d1cdfe8651497858e3e7efb7efd40d4dfbd60dbbe563bf5d7dc30badff22c34204e918fa4086259b357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
